server:
  port: 8899
  servlet:
    context-path: /xxl-job-admin

management:
  server:
    servlet:
      context-path: /actuator
  health:
    mail:
      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:8001/wsw-cloud-config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type:
      hikari:
        minimum-idle: 10
        maximum-pool-size: 30
        auto-commit: true
        idle-timeout: 30000
        pool-name: HikariCP
        max-lifetime: 900000
        connection-timeout: 10000
        connection-test-query: SELECT 1
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
  mail:
    host: smtp.qq.com
    port: 25
    username: 455618871@qq.com
    password: derjzlpgbunicbdf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml

xxl:
  job:
    login:
      username: admin
      password: 123456
    accessToken:
    i18n: zh_CN
    #触发池
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    logretentiondays: 30
