server:
  port: 9040
  servlet:
    session:
      cookie:
        name: sentinel_dashboard_cookie
#    context-path: /sentinel-dashboard
nacos:
  server:
    address: 127.0.0.1:8849
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
sentinel:
  dashboard:
    version: ${project.version}
logging:
  level:
    org:
      springframework:
        web: INFO
auth:
  username: ap-sentinel
  password: 9eba0b482d2640ce966f0c3b1bfeeeb0
  filter:
    exclude-urls: /,/auth/login,/auth/logout,/registry/machine,/version
    exclude-url-suffixes: htm,html,js,css,map,ico,ttf,woff,png