server:
  port: 8848
  servlet:
    context-path: /nacos
  tomcat:
    basedir: logs

spring:
  datasource:
    platform: mysql

db:
  num: 1
  url.0: jdbc:mysql://localhost:8001/wsw-cloud-nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=UTC
  user: root
  password: root

nacos:
  cmdb:
    dumpTaskInterval: 3600
    eventTaskInterval: 10
    labelTaskInterval: 300
    loadDataAtStart: false
  security:
    ignore:
      url: /,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**
  core:
    auth:
      enabled: true
      system:
        type: nacos
      default.token.secret.key: WSW012345678901234567890123456789012345678901234567890123456789
  naming:
    empty-service:
      auto-clean: true
      clean:
        initial-delay-ms: 50000
        period-time-ms: 30000

tldSkipPatterns: derbyLocale_*.jar,jaxb-api.jar,jsr173_1.0_api.jar,jaxb1-impl.jar,activation.jar

management:
  metrics:
    export:
      elastic:
        enabled: false
      influx:
        enabled: false
